using System;
using System.Data;
using System.Data.SqlClient;
using lmDatasets;

namespace atriumDAL
{
	/// <summary>
	/// Class generated by sgen 
	/// based on Hearing table 
	/// in atrium database
	/// on 12/11/2012
	/// </summary>
	public partial class HearingDAL:atDAL.ObjectDAL
	{

    	internal HearingDAL(atriumDALManager pDALManager) :base(pDALManager)
		{
		    Init();
		}

        private void Init()
        {

            this.sqlDa.TableMappings.AddRange(new System.Data.Common.DataTableMapping[] {

		        new System.Data.Common.DataTableMapping("Table", "Hearing", new System.Data.Common.DataColumnMapping[] 
                {
		            new System.Data.Common.DataColumnMapping("HearingID", "HearingID"),
		            new System.Data.Common.DataColumnMapping("SSTCaseId", "SSTCaseId"),
		            new System.Data.Common.DataColumnMapping("FileID", "FileID"),
		            new System.Data.Common.DataColumnMapping("ApptId", "ApptId"),
		            new System.Data.Common.DataColumnMapping("MemberId", "MemberId"),
		            new System.Data.Common.DataColumnMapping("HearingStatus", "HearingStatus"),
		            new System.Data.Common.DataColumnMapping("HearingType", "HearingType"),
		            new System.Data.Common.DataColumnMapping("HearingMethodId", "HearingMethodId"),
		            new System.Data.Common.DataColumnMapping("entryUser", "entryUser"),
		            new System.Data.Common.DataColumnMapping("entryDate", "entryDate"),
		            new System.Data.Common.DataColumnMapping("updateUser", "updateUser"),
		            new System.Data.Common.DataColumnMapping("updateDate", "updateDate"),
		            new System.Data.Common.DataColumnMapping("ts", "ts"),
		            new System.Data.Common.DataColumnMapping("SSTDecisionId", "SSTDecisionId"),
                    new System.Data.Common.DataColumnMapping("AdjReasonId", "AdjReasonId"),
                    new System.Data.Common.DataColumnMapping("SecurityPIN", "SecurityPIN"),
                    new System.Data.Common.DataColumnMapping("HearingRoomId", "HearingRoomId"),
                    new System.Data.Common.DataColumnMapping("SCOfficeId", "SCOfficeId"),
		        })
            });

            // 
            // sqlSelect
            // 
            this.sqlSelect.CommandType = System.Data.CommandType.StoredProcedure;
            this.sqlSelect.Connection = myDALManager.SqlCon;

            this.sqlSelectAll.CommandText = "[HearingSelect]";
            this.sqlSelectAll.CommandType = System.Data.CommandType.StoredProcedure;
            this.sqlSelectAll.Connection = myDALManager.SqlCon;
            this.sqlSelectAll.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));

            // 
            // sqlInsert
            // 
            this.sqlInsert.CommandText = "[HearingInsert]";
            this.sqlInsert.CommandType = System.Data.CommandType.StoredProcedure;
            this.sqlInsert.Connection = myDALManager.SqlCon;
            this.sqlInsert.Parameters.Add(new SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));

            this.sqlInsert.Parameters.Add(new SqlParameter("@HearingID", SqlDbType.Int, 10, "HearingID"));
            this.sqlInsert.Parameters["@HearingID"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@SSTCaseId", SqlDbType.Int, 10, "SSTCaseId"));
            this.sqlInsert.Parameters["@SSTCaseId"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@FileID", SqlDbType.Int, 10, "FileID"));
            this.sqlInsert.Parameters["@FileID"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@ApptId", SqlDbType.Int, 10, "ApptId"));
            this.sqlInsert.Parameters["@ApptId"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@MemberId", SqlDbType.Int, 10, "MemberId"));
            this.sqlInsert.Parameters["@MemberId"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@HearingStatus", SqlDbType.Int, 10, "HearingStatus"));
            this.sqlInsert.Parameters["@HearingStatus"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@HearingType", SqlDbType.Int, 10, "HearingType"));
            this.sqlInsert.Parameters["@HearingType"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@HearingMethodId", SqlDbType.Int, 10, "HearingMethodId"));
            this.sqlInsert.Parameters["@HearingMethodId"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@entryUser", SqlDbType.NVarChar, 20, "entryUser"));
            this.sqlInsert.Parameters["@entryUser"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@entryDate", SqlDbType.SmallDateTime, 24, "entryDate"));
            this.sqlInsert.Parameters["@entryDate"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@updateUser", SqlDbType.NVarChar, 20, "updateUser"));
            this.sqlInsert.Parameters["@updateUser"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@updateDate", SqlDbType.SmallDateTime, 24, "updateDate"));
            this.sqlInsert.Parameters["@updateDate"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@ts", SqlDbType.Timestamp, 50, "ts"));
            this.sqlInsert.Parameters["@ts"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@SSTDecisionId", SqlDbType.Int, 10, "SSTDecisionId"));
            this.sqlInsert.Parameters["@SSTDecisionId"].SourceVersion = DataRowVersion.Current;
            
            this.sqlInsert.Parameters.Add(new SqlParameter("@AdjReasonId", SqlDbType.Int, 10, "AdjReasonId"));
            this.sqlInsert.Parameters["@AdjReasonId"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@SecurityPIN", SqlDbType.Int, 10, "SecurityPIN"));
            this.sqlInsert.Parameters["@SecurityPIN"].SourceVersion = DataRowVersion.Current;
            
            this.sqlInsert.Parameters.Add(new SqlParameter("@HearingRoomId", SqlDbType.Int, 10, "HearingRoomId"));
            this.sqlInsert.Parameters["@HearingRoomId"].SourceVersion = DataRowVersion.Current;
            this.sqlInsert.Parameters.Add(new SqlParameter("@SCOfficeId", SqlDbType.Int, 10, "SCOfficeId"));
            this.sqlInsert.Parameters["@SCOfficeId"].SourceVersion = DataRowVersion.Current;

            // 
            // sqlUpdate
            // 
            this.sqlUpdate.CommandText = "[HearingUpdate]";
            this.sqlUpdate.CommandType = System.Data.CommandType.StoredProcedure;
            this.sqlUpdate.Connection = myDALManager.SqlCon;
            this.sqlUpdate.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));

            this.sqlUpdate.Parameters.Add(new SqlParameter("@HearingID", SqlDbType.Int, 10, "HearingID"));
            this.sqlUpdate.Parameters["@HearingID"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@SSTCaseId", SqlDbType.Int, 10, "SSTCaseId"));
            this.sqlUpdate.Parameters["@SSTCaseId"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@FileID", SqlDbType.Int, 10, "FileID"));
            this.sqlUpdate.Parameters["@FileID"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@ApptId", SqlDbType.Int, 10, "ApptId"));
            this.sqlUpdate.Parameters["@ApptId"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@MemberId", SqlDbType.Int, 10, "MemberId"));
            this.sqlUpdate.Parameters["@MemberId"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@HearingStatus", SqlDbType.Int, 10, "HearingStatus"));
            this.sqlUpdate.Parameters["@HearingStatus"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@HearingType", SqlDbType.Int, 10, "HearingType"));
            this.sqlUpdate.Parameters["@HearingType"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@HearingMethodId", SqlDbType.Int, 10, "HearingMethodId"));
            this.sqlUpdate.Parameters["@HearingMethodId"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@entryUser", SqlDbType.NVarChar, 20, "entryUser"));
            this.sqlUpdate.Parameters["@entryUser"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@entryDate", SqlDbType.SmallDateTime, 24, "entryDate"));
            this.sqlUpdate.Parameters["@entryDate"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@updateUser", SqlDbType.NVarChar, 20, "updateUser"));
            this.sqlUpdate.Parameters["@updateUser"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@updateDate", SqlDbType.SmallDateTime, 24, "updateDate"));
            this.sqlUpdate.Parameters["@updateDate"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@ts", SqlDbType.Timestamp, 50, "ts"));
            this.sqlUpdate.Parameters["@ts"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@SSTDecisionId", SqlDbType.Int, 10, "SSTDecisionId"));
            this.sqlUpdate.Parameters["@SSTDecisionId"].SourceVersion = DataRowVersion.Current;

            this.sqlUpdate.Parameters.Add(new SqlParameter("@AdjReasonId", SqlDbType.Int, 10, "AdjReasonId"));
            this.sqlUpdate.Parameters["@AdjReasonId"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@SecurityPIN", SqlDbType.Int, 10, "SecurityPIN"));
            this.sqlUpdate.Parameters["@SecurityPIN"].SourceVersion = DataRowVersion.Current;

            this.sqlUpdate.Parameters.Add(new SqlParameter("@HearingRoomId", SqlDbType.Int, 10, "HearingRoomId"));
            this.sqlUpdate.Parameters["@HearingRoomId"].SourceVersion = DataRowVersion.Current;
            this.sqlUpdate.Parameters.Add(new SqlParameter("@SCOfficeId", SqlDbType.Int, 10, "SCOfficeId"));
            this.sqlUpdate.Parameters["@SCOfficeId"].SourceVersion = DataRowVersion.Current;

            // 
            // sqlDelete
            // 
            this.sqlDelete.CommandText = "[HearingDelete]";
            this.sqlDelete.CommandType = System.Data.CommandType.StoredProcedure;
            this.sqlDelete.Connection = myDALManager.SqlCon;
            this.sqlDelete.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlDelete.Parameters.Add(new System.Data.SqlClient.SqlParameter("@HearingID", System.Data.SqlDbType.Int, 4, "HearingID"));
            this.sqlDelete.Parameters["@HearingID"].SourceVersion = DataRowVersion.Original;
            this.sqlDelete.Parameters.Add(new System.Data.SqlClient.SqlParameter("@ts", System.Data.SqlDbType.Timestamp, 50, "ts"));
            this.sqlDelete.Parameters["@ts"].SourceVersion = DataRowVersion.Original;

        }

		public SST.HearingDataTable Load()
		{
			this.sqlDa.SelectCommand=sqlSelectAll;

            SST.HearingDataTable dt=new SST.HearingDataTable();
			Fill(dt);
            return dt;
        }

		public SST.HearingDataTable Load(int HearingID)
		{
			this.sqlDa.SelectCommand=sqlSelect;
			this.sqlSelect.Parameters.Clear();
			this.sqlSelect.CommandText = "[HearingSelectByHearingID]";
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@HearingID", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));

			this.sqlSelect.Parameters["@HearingID"].Value=HearingID;

            SST.HearingDataTable dt=new SST.HearingDataTable();
			Fill(dt);
            return dt;
		}

		public SST.HearingDataTable LoadByApptId(int ApptId)
		{
			this.sqlDa.SelectCommand=sqlSelect;
			this.sqlSelect.Parameters.Clear();
			this.sqlSelect.CommandText = "[HearingSelectByApptId]";
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@ApptId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters["@ApptId"].Value=ApptId;

            SST.HearingDataTable dt=new SST.HearingDataTable();
			Fill(dt);
            return dt;
		}

		public SST.HearingDataTable LoadByMemberId(int MemberId)
		{
			this.sqlDa.SelectCommand=sqlSelect;
			this.sqlSelect.Parameters.Clear();
			this.sqlSelect.CommandText = "[HearingSelectByMemberId]";
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@MemberId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters["@MemberId"].Value=MemberId;

            SST.HearingDataTable dt=new SST.HearingDataTable();
			Fill(dt);
            return dt;
		}

		public SST.HearingDataTable LoadByFileID(int FileID)
		{
			this.sqlDa.SelectCommand=sqlSelect;
			this.sqlSelect.Parameters.Clear();
			this.sqlSelect.CommandText = "[HearingSelectByFileID]";
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@FileID", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters["@FileID"].Value=FileID;

            SST.HearingDataTable dt=new SST.HearingDataTable();
			Fill(dt);
            return dt;
		}

		public SST.HearingDataTable LoadBySSTCaseId(int SSTCaseId)
		{
			this.sqlDa.SelectCommand=sqlSelect;
			this.sqlSelect.Parameters.Clear();
			this.sqlSelect.CommandText = "[HearingSelectBySSTCaseId]";
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@SSTCaseId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
			this.sqlSelect.Parameters["@SSTCaseId"].Value=SSTCaseId;

            SST.HearingDataTable dt=new SST.HearingDataTable();
			Fill(dt);
            return dt;
		}

        public SST.HearingDataTable LoadByHearingRoomId(int HearingRoomId)
        {
            this.sqlDa.SelectCommand = sqlSelect;
            this.sqlSelect.Parameters.Clear();
            this.sqlSelect.CommandText = "[HearingSelectByHearingRoomId]";
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@HearingRoomId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters["@HearingRoomId"].Value = HearingRoomId;

            SST.HearingDataTable dt = new SST.HearingDataTable();
            Fill(dt);
            return dt;
        }

        public SST.HearingDataTable LoadBySCOfficeId(int SCOfficeId)
        {
            this.sqlDa.SelectCommand = sqlSelect;
            this.sqlSelect.Parameters.Clear();
            this.sqlSelect.CommandText = "[HearingSelectBySCOfficeId]";
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@SCOfficeId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters["@SCOfficeId"].Value = SCOfficeId;

            SST.HearingDataTable dt = new SST.HearingDataTable();
            Fill(dt);
            return dt;
        }

        public SST.HearingDataTable LoadSecurityPINByMemberId(int MemberId)
        {
            this.sqlDa.SelectCommand = sqlSelect;
            this.sqlSelect.Parameters.Clear();
            this.sqlSelect.CommandText = "[HearingSelectSecurityPINByMemberId]";
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@MemberId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters["@MemberId"].Value = MemberId;

            SST.HearingDataTable dt = new SST.HearingDataTable();
            Fill(dt);
            return dt;
        }

	}

}