using System;
using System.Data;
using System.Data.SqlClient;
using lmDatasets;


namespace atriumDAL
{
    /// <summary>
    /// Class generated by sgen 
    /// based on RAClientImpact table 
    /// in lawmate database
    /// on 2006/06/16
    /// </summary>
    public partial class RAClientImpactDAL : atDAL.ObjectDAL
    {
        public atriumDB.RAClientImpactDataTable LoadByRiskAssessId(int RiskAssessId)
        {
            this.sqlDa.SelectCommand = sqlSelect;
            this.sqlSelect.Parameters.Clear();
            this.sqlSelect.CommandText = "[RAClientImpactSelectByRiskAssessId]";
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RiskAssessId", System.Data.SqlDbType.Int, 10, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));

            this.sqlSelect.Parameters["@RiskAssessId"].Value = RiskAssessId;

            atriumDB.RAClientImpactDataTable dt = new atriumDB.RAClientImpactDataTable();
            Fill(dt);
            return dt;
        }

    }
}
