using System;
using System.Data;
using System.Data.SqlClient;
using lmDatasets;


namespace atriumDAL
{
    /// <summary>
    /// Class generated by sgen 
    /// based on RiskAssessment table 
    /// in lawmate database
    /// on 2006/06/16
    /// </summary>
    public partial class RiskAssessmentDAL : atDAL.ObjectDAL
    {
        public atriumDB.RiskAssessmentDataTable LoadByFileId(int fileId)
        {
            this.sqlDa.SelectCommand = sqlSelect;
            this.sqlSelect.Parameters.Clear();
            this.sqlSelect.CommandText = "[RiskAssessmentSelectByFileId]";
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@RETURN_VALUE", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.ReturnValue, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));
            this.sqlSelect.Parameters.Add(new System.Data.SqlClient.SqlParameter("@FileId", System.Data.SqlDbType.Int, 4, System.Data.ParameterDirection.Input, false, ((System.Byte)(10)), ((System.Byte)(0)), "", System.Data.DataRowVersion.Current, null));

            this.sqlSelect.Parameters["@FileId"].Value = fileId;

            atriumDB.RiskAssessmentDataTable dt = new atriumDB.RiskAssessmentDataTable();
            Fill(dt);
            return dt;
        }

    }
}
